= Practising the Java Module System
:doctype: book
:encoding: utf-8
:lang: en
:toc: left
:force-include:

To start hands-on lab session, first you should clone the https://github.com/codecop/practicing-java9-module-system[repository] or download the zipped version here https://github.com/codecop/practicing-java9-module-system/archive/codecop.zip

[NOTE]
====
. Attendees who want to practice should install required tools in advance link:WORKSHOP_REQUIREMENTS.adoc[] .

. It is an open workshop, you can hold an event in your user group or company.
====

[NOTE]
====
Presentation is accessible here. If you need an editable version of it, just send an email to rahmanusta@kodedu.com

https://docs.google.com/presentation/d/1nZpErxa8OC3_uaKBX4sCDUryLTz5FS7aXmnvydLYyeE/edit?usp=sharing
====

== *Practice 1*: Generate JREs

JLink tool allows you to create different scale of JREs. Every application has different scale, and it is not required to use a module that we don't need!

[source,bash]
----
mkdir generate-image
cd generate-image

// Run
generate-images.bat or ./generate-images.sh
----

After generation is completed, verify that you have ``java.base``, ``java.desktop``, ``java.se``, and ``java.se.ee`` included JREs in the directory. Check folder sizes (with ``du -sh``) and add them to your notepad.

== *Practice 2*: Create a hello world module

Create a "Hello world!" module. Compile, Package, and Run it.

1) Get the following directory structure, check the ``module-info.java`` and ``Hello.java`` classes.

[tree]
----
hello-world
└── src
    ├── module-info.java
    └── com
        └── foo
            └── Hello.java
----

.module-info.java
[source,java]
----
module com.foo {
    // no definition yet
}
----

.com.foo.Hello.java
[source,java]
----
package com.foo;

public class Hello {

    public static void main(String[] args) {
        System.out.println("Hello world!");
    }

}
----

2) Compile the module artefacts

``module-info.java`` is a module descriptor file. It should be compiled along with other classes in the module.

[source,bash]
----
cd hello-world
javac src/module-info.java src/com/foo/Hello.java -d dist
----

After compilation, ``hello-world/dist`` folder should include compiled module descriptor and ``Hello.class``.

[tree]
----
hello-world
└── dist
    ├── module-info.class
    └── com
        └── foo
            └── Hello.class
----

3) Run the module with ``dist`` folder

Add ``dist`` directory to the module path to be able to resolve *com.foo* module inside, and run *com.foo.Hello* class inside *com.foo* module.

[source,java]
----
java --module-path dist -m com.foo/com.foo.Hello
// Hello world!
----

4) Package the modular app

We can package standard Java module as a JAR (Java Archive) file. Then, we call it as modular JAR file.

[source,bash]
----
jar --create --file hello.jar --main-class=com.foo.Hello -C dist .
----

After the jar command completed, verify that you have ``hello.jar`` file in the current directory.

5) Run the module with a modular JAR file

We can also add modular JAR files to the --module-path.

[source,bash]
----
java --module-path hello.jar -m com.foo/com.foo.Hello
// Hello world!
----

6) Link

jlink is a link tool for Java 9. It creates a portable bundle of your application and JRE.

[source,bash]
----
jlink --module-path "%JAVA_HOME%/jmods;hello.jar" --add-modules com.foo --launcher hello=com.foo/com.foo.Hello --output release <1>

jlink --module-path $JAVA_HOME/jmods:hello.jar --add-modules com.foo --launcher hello=com.foo/com.foo.Hello --output release <2>
----
<1> For win
<2> For *nix

After link, you will have a special JRE which has Hello module included. You can run the module with produced launcher.

[source,bash]
----
cd release
bin\hello.bat <1>
./bin/hello <2>
----
<1> for win
<2> for *nix

Check out the ``hello`` executable.

== *Practice 3*: Control access between modules

Let's use `exports` and `requires` keywords to control *access* between modules.

exports:: declares which package(s) will be readable to outside modules.
requires:: declares which module(s) are needed to read/access.

.module-core directory
[width="100%",options="header",cols="1a,1a"]
|====================
| printer-client module | printer-impl module
|

[tree]
----
printer-client
└── src
    ├── module-info.java
    └── com
        └── printer
            └── client
                └── PrinterClient.java
----

|

[tree]
----
printer-impl
└── src
    ├── module-info.java
    └── com
        └── printer
            └── impl
                └── Printer.java
----

|====================

In this practice, you are going to play with ``exports`` and ``requires`` keywords to understand them easily.

Case 1:: When exports and requires are not declared in module descriptor.

Open `module-core` directory, and check that `printer-client/src/module-info.java` doesn't include `requires` and `printer-impl/src/module-info.java` doesn't include `exports` keywords.

Compile printer-impl and printer-client modules, and log that how Java module system prevents access when `exports` and `requires` are missed.

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

////
printer-client\src\com\printer\client\PrinterClient.java:3: error: package com.printer.impl is not visible
import com.printer.impl.Printer;
                  ^
  (package com.printer.impl is declared in module com.printer.impl, but module com.printer.client does not read it)
1 error
////

Case2:: When exports declared, but requires is not declared

Update `printer-impl/src/module-info.java` descriptor file to export `com.printer.impl` package to other modules.

.printer-impl/src/module-info.java
[source,java]
----
module com.printer.impl {
    exports com.printer.impl;
}
----

Compile ``printer-impl`` and ``printer-client`` modules, and log that how Java module system prevents access when `requires` is missed.

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

////
printer-client\src\com\printer\client\PrinterClient.java:3: error: package com.printer.impl is not visible
import com.printer.impl.Printer;
                  ^
  (package com.printer.impl is declared in module com.printer.impl, but module com.printer.client does not read it)
1 error
////

Case 3:: When requires declared, but exports is not declared

Update `printer-impl/src/module-info.java` descriptor file to not export any package, and update `printer-client/src/module-info.java` to require printer-impl module.

.printer-impl/src/module-info.java
[source,java]
----
module com.printer.impl {

}
----

.printer-client/src/module-info.java
[source,java]
----
module com.printer.client {
    requires com.printer.impl;
}
----

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

Compile ``printer-impl`` and ``printer-client`` modules, and log that how Java module system prevents access when `exports` is missed.

////
printer-client\src\com\printer\client\PrinterClient.java:3: error: package com.printer.impl is not visible
import com.printer.impl.Printer;
                  ^
  (package com.printer.impl is declared in module com.printer.impl, which does not export it)
1 error
////

Case 4:: When both requires and exports are declared

Update `printer-impl/src/module-info.java` descriptor file to export `com.printer.impl` package, and update `printer-client/src/module-info.java` to require `com.printer.impl` module.

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

Compile printer-impl and printer-client modules, and log that how Java module system controls access among modules successfully.

////
Success
////

== *Practice 4*: Using Auto-modules

Auto-modules is designed for smooth migration to the Java module system.

When a non-modular classic JAR file is added to module path (``--module-path`` or ``-p``), then it becomes an auto-module.

[TIP]
====
All packages of an auto-module are readable by other modules.
====

Open `auto-module` directory, and check that there is a non-modular ``jansi-1.17.1.jar`` file. Then, edit module descriptors for both ``printer-client`` and ``printer-impl`` modules.

.printer-client/src/module-info.java
[source,java]
----
module com.printer.client {
    requires com.printer.impl;
}
----

.printer-impl/src/module-info.java
[source,java]
----
module com.printer.impl {
    exports com.printer.impl;

    requires jansi; <1>
}
----
<1> ``jansi`` is a non-modular Jar file and it behaves like a module (auto-module) if it is added to module path. Module name is resolved without version part from the file name.

[source,java]
----
package com.printer.impl;

import org.fusesource.jansi.AnsiConsole;

import static org.fusesource.jansi.Ansi.Color.BLUE;
import static org.fusesource.jansi.Ansi.Color.RED;
import static org.fusesource.jansi.Ansi.ansi;

public class Printer {
    public void print(String message) {
        AnsiConsole.systemInstall();
        System.out.println(ansi().fg(BLUE).a("This is a colored output!"));
        System.out.println(ansi().fg(RED).a(message));
    }
}
----

.Compile modules
[source,bash]
----
javac printer-impl/src/module-info.java printer-impl/src/com/printer/impl/Printer.java -p lib -d dist/printer-impl

javac printer-client/src/module-info.java printer-client/src/com/printer/client/PrinterClient.java -p dist/printer-impl;lib -d dist/printer-client
----

.Run modules
[source,bash]
----
java --module-path dist;lib -m com.printer.client/com.printer.client.PrinterClient
----

After compile, run the auto-module app, verify that console output is coloured with jansi library.

== *Practice 5*: Using Unnamed modules

In this practice, you are going to test access from an unnamed module to a module.

Open `unnamed-module` folder, and check that `printer-client` module doesn't have a module descriptor file, and compile it as a non-module, and the `printer-impl` module.

[source,bash]
----
javac printer-impl/src/module-info.java printer-impl/src/com/printer/impl/Printer.java -d dist/printer-impl <1>

javac printer-client/src/com/printer/client/PrinterClient.java -p dist/printer-impl --add-modules c
om.printer.impl -d dist/printer-client <2>
----
<1> Compile printer-impl module
<2> Compile printer-client without ``module-info.java``

After compilation, run non-modular `printer-client` and verify that it is able to access exported packages from unnamed module.

[source,bash]
----
java --module-path dist --add-modules com.printer.impl <1>
     -cp dist/printer-client com.printer.client.PrinterClient <2>
----
<1> ``com.printer.impl`` is added to module path
<2> ``printer-client`` is added to classpath

// include::OPEN_ACCESS_OPTIONAL.adoc[]

== *Practice 6*: Reflection

See link:OPEN_ACCESS_OPTIONAL.adoc[]

The end.

== License

https://opensource.org/licenses/MIT[MIT]
